config/routes.rb
Storage::Application.routes.draw do

  devise_for :users, :controllers => {:sessions => 'user'}

  devise_scope :user do
    get 'users/:id' => 'user#show'
    get 'user' => 'user#index'
  end

  resources :listings
  resources :user

  get 'listings/rent/:id' => "listings#rent"
  root 'app#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user

  scope :rented_by, ->(user_id) { where("renter_id IS ?", user_id) }

  def rented?
    renter_id.present?
  end

  def to_s
    "#{width * length} sq ft @ #{street_address}, #{city}, #{state} #{zip_code}"
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['city LIKE ?', "%#{search}"])
    else
      find(:all)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :listings, dependent: :destroy

  def ready_to_buy?
    #TODO this should check that everything in their profile is accurate
    true
  end

  def buy listing
    # TODO charge their credit card, send out emails n shit
    listing.renter_id = id
    # Also TODO, never save!, always if save blah blah
    listing.save!
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def index
    @title = "Home"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:first_name, :last_name, :phone, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
    }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  def index
    @title = "Listings"
    if !params[:search].nil? and params[:search] != ""
      @listings = Listing.where("listings.renter_id IS NULL")
      @listings = @listings.where(city: params[:search])
    elsif !params[:type].nil? and params[:type] != "" and params[:type] != "None"
      @listings = Listing.where("listings.renter_id IS NULL")
      @listings = @listings.where(storage_type: params[:type])
      if !params[:low_price].nil? and params[:low_price] != "" and !params[:high_price].nil? and params[:high_price] != ""
        @listings = @listings.where(:price => params[:low_price]..params[:high_price])
      end
    elsif !params[:low_price].nil? and params[:low_price] != "" and !params[:high_price].nil? and params[:high_price] != ""
      @listings = Listing.where("listings.renter_id IS NULL")
      @listings = @listings.where(:price => params[:low_price]..params[:high_price])
      if !params[:type].nil? and params[:type] != "" and params[:type] != "None"
        @listings = @listings.where(storage_type: params[:type])
      end
    else
      @listings = Listing.where("listings.renter_id IS NULL")
    end
  end

  def show
    @listing = Listing.find params[:id]
  end

  def new
    @title = "New Listing"
    @listing = Listing.new
  end

  def edit
    @title = "Edit Listing"
    @listing = Listing.find(params[:id])
  end

  def update
    
  end

  def create
    @listing = current_user.listings.create(listing_params)
    if @listing.save
      redirect_to action: :index
    else
      render :new
    end
  end

  # custom
  
  def rent
    @listing = Listing.find params[:id] 
    if @listing.rented?
      flash[:warning] = "Listing already rented"
      redirect_back_or_default root_path
    end

    if current_user.ready_to_buy?
      current_user.buy @listing
      flash[:notice] = "Successfully rented space!"
      redirect_to controller: "user", action: "show", id: current_user.id
    else
      flash[:warning] = "Please fill in the rest of your information"
      redirect_to controller: "user", action: "show", id: current_user.id
    end
  end

  private

  def listing_params
    params.require(:listing).permit(:start_date, :end_date, :street_address, :city, :state, :zip_code, :width, :length, :price, :storage_type)
  end
end

app/controllers/user_controller.rb
class UserController < Devise::SessionsController
  before_filter :authenticate_user!, :except => [:index]
  def index
    if signed_in?
      redirect_to action: "show", id: current_user.id
    else 
      redirect_to new_user_session_path
    end
  end

  def show
    id = params[:id]
    @title = "User Listings"
    @user_inspecting = User.find id
    @listings = @user_inspecting.listings

    if signed_in? and @user_inspecting.id == current_user.id
      @renting = Listing.rented_by @user_inspecting.id
    end
  end

  def edit

  end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/user_helper.rb
module UserHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/app/index.html.haml
%div.jumbotron
  %h4 Storage Startup is the best place online to convienently find affordable storage and rent it to others. 
  %form.form-inline{:action => listings_path, :method => 'get'}
    .form-group
      =text_field_tag :search, params[:search], :style => 'width: 250px;', :placeholder => 'Where are you looking for space?', :class => 'form-control'
    %button.btn.btn-default{:type => 'submit'}Search
  %h4 - OR -
  %a.btn.btn-primary{:href => new_listing_path}List a New Space!

app/views/layouts/application.html.haml
%html
  %head
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "jquery-1.10.2.min.js"
    %script{:src => "/js/main.js", :type => "text/javascript"}
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %title= "Storage Startup | #{@title}"
  %body
    #wrap
      .container
        = render "shared/header"
        - if flash[:notice]
          .flash-notice #{flash[:notice]}
        - if flash[:alert]
          .flash-error #{flash[:alert]}
        = yield 
    .footer 
      .container
        %br
        %p.text-muted
          © Storage Startup 2013 

app/views/listings/_form.html.haml
%div.form-inline.form-generic
  %h4 Create a New Listing
  %label Storage Type 
  =form_for @listing do |f|
    %div.form-group
      %select.form-control{:name => 'listing[storage_type]'}
        %option{:value => 'Closet'}Closet 
        %option{:value => 'Bedroom'}Bedroom
        %option{:value => 'Living Room'}Living Room
    %div.form-group
      =f.text_field :width, :class => 'form-control', :placeholder => 'Width (ft)'
      x
      =f.text_field :length, :class => 'form-control', :placeholder => 'Length (ft)'
    %br
    %br
    %label Location 
    %br
    %div.form-group
      =f.text_field :street_address, :class => 'form-control', :placeholder => 'Street Address'
      ,
      =f.text_field :city, :class => 'form-control', :placeholder => 'City'
      %br
      =f.text_field :state, :class => 'form-control', :placeholder => 'State'
      ,
      =f.text_field :zip_code, :class => 'form-control', :placeholder => 'Zip Code'
    %br
    %br
    %label Pricing
    %br
    %div.form-group
      =f.text_field :price, :class => 'form-control', :placeholder => '$/mo.'
    %br
    %br
    %div.form-group.col-sm-offset-9
      - if user_signed_in?
        %button.btn.btn-default{:type => 'submit'}Submit
      - else
        %a.btn.btn-default Next
        

app/views/listings/edit.html.haml
=render "form"

app/views/listings/index.html.haml
.col-xs-3
  .list-group
    .list-group-item
      = form_tag listings_path, :method => :get do
        %label Filter by Storage Type
        %br
        - if params[:type] == 'None'
          = radio_button_tag(:type, 'None', :checked => true)
        - else
          = radio_button_tag(:type, 'None')
        = label_tag('None')
        %br
        - if params[:type] == 'Closet'
          = radio_button_tag(:type, 'Closet', :checked => true)
        - else
          = radio_button_tag(:type, 'Closet')
        = label_tag('Closet')
        %br
        - if params[:type] == 'Bedroom'
          = radio_button_tag(:type, 'Bedroom', :checked => true)
        - else
          = radio_button_tag(:type, 'Bedroom')
        = label_tag('Bedroom')
        %br
        - if params[:type] == 'Living Room'
          = radio_button_tag(:type, 'Living Room', :checked => true)
        - else
          = radio_button_tag(:type, 'Living Room')
        = label_tag('Living Room')
        %br
        %br
        %label Filter by Price/mo.
        .text-center
          %input.form-control{:type => 'text', :value => params[:low_price],:name => 'low_price', :placeholder => 'Low', :style => 'width: 70px; float: left; margin-right: 10px;'}
          %input.form-control{:type => 'text', :value => params[:high_price], :name => 'high_price', :placeholder => 'High', :style => 'width: 70px; float: left;'}
          .form-group
            = submit_tag 'Filter', name: nil, :class => 'btn btn-primary'
.col-xs-9
  = render 'shared/listings', listings: @listings

app/views/listings/new.html.haml
=render "form"

app/views/listings/show.html.haml
%h3 #{@listing.width * @listing.length} sq ft Available @ #{@listing.street_address}, #{@listing.city}, #{@listing.state} #{@listing.zip_code}
%h4 
  By 
  = link_to "#{User.find(@listing.user_id).first_name}", User.find(@listing.user_id)
.col-xs-9
  .row
    .col-xs-6.col-md-3
      %a.thumbnail
        %img{:src => 'http://www.fakenamegenerator.com/dummyimage/171x180/CCCCCC/000000/1'}
    .col-xs-6.col-md-3
      %a.thumbnail
        %img{:src => 'http://www.fakenamegenerator.com/dummyimage/171x180/CCCCCC/000000/1'}
    .col-xs-6.col-md-3
      %a.thumbnail
        %img{:src => 'http://www.fakenamegenerator.com/dummyimage/171x180/CCCCCC/000000/1'}
    .col-xs-6.col-md-3
      %a.thumbnail
        %img{:src => 'http://www.fakenamegenerator.com/dummyimage/171x180/CCCCCC/000000/1'}
.col-xs-3
  %div.right.rent-box
    %h2="$#{@listing.price}/mo."
    = link_to "Rent This Unit", { action: "rent", id: @listing.id}, class: "btn btn-large btn-success"
    
- if @listing.rented?
  Sorry, this unit is already taken
- else

app/views/shared/_header.html.haml
%div.header
  %ul.nav.nav-pills.pull-right
    %li
      = link_to "List Space!", new_listing_path
    - if user_signed_in?
      %li.dropdown
        %a.dropdown-toggle{'data-toggle' => 'dropdown'}
          - if current_user.first_name != ""
            #{current_user.first_name}
          - else
            Profile
          %b.caret
        %ul.dropdown-menu
          %li
            = link_to "Profile", user_index_path
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete
    - else
      %li
        = link_to "Login", new_user_session_path
      %li
        = link_to "Sign Up", new_user_registration_path
  %h1.logo 
    %a{:href => '/'}Storage Startup 
  %hr

app/views/shared/_listings.html.haml
-# Should always be called with a local variable 'listings'
- if @listings.nil? or @listings.empty?
  %h3 No listings available.
  = link_to "Add One", new_listing_path
- else
  -listings.each do |listing|
    %div.listing-box
      %div.left
        = link_to listing do
          %h3.listing-heading=listing.to_s
        %p.listing-description
          #{listing.storage_type} available by 
          = link_to "#{User.find(listing.user_id).first_name}", User.find(listing.user_id)
      %div.right
        %h3="$#{listing.price}/mo."

app/views/shared/_rentals.html.haml
-# Should always be called with a local variable 'rentals'
- if rentals.nil? or rentals.empty?
  %h3 You're not currently renting any property
  = link_to "Find some space!", root_path
- else
  -rentals.each do |rental|
    %div.listing-box
      %div.left
        %h3.listing-heading="#{rental.width * rental.length} sq ft @ #{rental.street_address}, #{rental.city}, #{rental.state} #{rental.zip_code}"
        %p.listing-description="#{rental.storage_type}"
      %div.right
        %h3="$#{rental.price}/mo."

app/views/user/show.html.haml
- if signed_in? and current_user.id == @user_inspecting.id
  .col-xs-3
    .list-group
      %a.spaces-tab.list-group-item.active Your Spaces 
      %a.information-tab.list-group-item Personal Information 
- if signed_in? and current_user.id == @user_inspecting.id
  .col-xs-9
    .spaces-view
      - if signed_in? and current_user.id == @user_inspecting.id
        .text-center
          %button.listings-btn.btn.btn-primary.btn-lg.active Listed
          %button.renting-btn.btn.btn-default.btn-lg Renting
      .spaces-listed
        %br
        = render 'shared/listings', listings: @listings
      .spaces-rented
        %br
        = render 'shared/listings', listings: @listings
        - if signed_in? and current_user.id == @user_inspecting.id
          = render 'shared/rentals', rentals: @renting
    .information-view
      = render 'devise/registrations/edit' 
- else
  .col-xs-12
    .spaces-listed
      %h4 Listings 
      = render 'shared/listings', listings: @listings